environment:
  name: anymal_d
  env:
    num_envs: 4096
    num_observations: 179
    num_privileged_observations: 191
    env_spacing: 3.0
    num_actions: 12
    episode_length_s: 20
    send_timeouts: true
  terrain:
    mesh_type: "trimesh"
    horizontal_scale: 0.1
    vertical_scale: 0.005
    border_size: 25
    curriculum: false
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    max_init_terrain_level: 5
    terrain_length: 8
    terrain_width: 8
    num_rows: 10
    num_cols: 20
    terrain_proportions:
    - 0.15
    - 0.15
    - 0.25
    - 0.25
    - 0.2
    slope_treshold: 0.75
    measure_heights: false
  command:
    curriculum: false
    max_curriculum: 1.0
    num_commands: 4
    resampling_time: 10
    heading_command: false
    ranges:
      lin_vel_x:
      - -0.5
      - 0.5
      lin_vel_y:
      - -0.3
      - 0.3
      ang_vel_yaw:
      - -0.6
      - 0.6
      heading:
      - -3.14
      - 3.14
  asset:
    name: anymal_d
    default_dof_drive_mode: 3
    collapse_fixed_joints: true
    replace_cylinder_with_capsule: true
    flip_visual_attachments: true
    fix_base_link: false
    density: 0.001
    angular_damping: 0.0
    linear_damping: 0.0
    max_angular_velocity: 1000.0
    max_linear_velocity: 1000.0
    armature: 0.0
    thickness: 0.01
    disable_gravity: false
    foot_name: FOOT
    shank_name: SHANK
    thigh_name: THIGH
    penalize_contacts_on:
    - SHANK
    - THIGH
    terminate_after_contacts_on:
    - base
    self_collisions: 1
  normalization:
    obs_scales:
      lin_vel: 2.0
      ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05
      height_measurements: 1.0
      contact_forces: 0.0016666666666666668
    clip_observations: 100.0
    clip_actions: 100.0
  domain_randomization:
    randomize_friction: true
    friction_range:
    - 0.5
    - 1.2
    randomize_base_mass: true
    added_mass_range:
    - -7
    - 7
    push_robots: true
    push_interval_s: 15
    max_push_vel_xy: 0.3
  sim:
    dt: 0.005
    substeps: 1
    gravity:
    - 0.0
    - 0.0
    - -9.81
    up_axis: 1
    physics_engine: physx
    physx:
      num_threads: 10
      solver_type: 1
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.01
      rest_offset: 0.0
      bounce_threshold_velocity: 0.5
      max_depenetration_velocity: 1.0
      max_gpu_contact_pairs: 8388608
      default_buffer_size_multiplier: 5
      contact_collection: 1
  control:
    control_type: CPG_WBC
    joints:
    - HAA
    - HFE
    - KFE
    stiffness:
    - 80.0
    - 80.0
    - 80.0
    damping:
    - 2.0
    - 2.0
    - 2.0
    action_scale: 0.5
    decimation: 4
  viewer:
    ref_env: 0
    pos:
    - 10.0
    - 0.0
    - 6.0
    lookat:
    - 11.0
    - 5.0
    - 3.0
  rewards:
    base_height_target: 0.5
    max_contact_force: 500.0
    only_positive_rewards: true
    tracking_sigma: 0.25
    soft_dof_pos_limit: 1.0
    soft_dof_vel_limit: 1.0
    soft_torque_limit: 1.0
    scales:
      termination: -0.0
      tracking_lin_vel: 0.0
      tracking_ang_vel: 0.0
      lin_vel_z: -0.0
      exp_base_position: 3.0
      exp_base_orientation: 2.0
      exp_base_linear_velocity: 2.0
      exp_base_angular_velocity: 1.0
      exp_base_linear_acceleration: 2.0
      exp_base_angular_acceleration: 1.0
      foot_power: -0.3
      ang_vel_xy: 0.0
      orientation: -0.0
      torques: -1.0e-05
      dof_vel: -0.0
      dof_acc: -1.0e-06
      base_height: 0.0
      feet_air_time: 1.0
      collision: -0.0
      stumble: -1.0
      action_rate: -0.02
      stand_still: 0.0
      smoothness: -0.0
      swing_height: -0.000
      action_norm: -0.005
      consistency: 60.0
      foot_position_tracking: 2.0
      z_height: 10.0
      follow_joint_trajectory: -1.0
      desired_foot_position_wbc_tracking: -1.0
      desired_foot_velocity_wbc_tracking: -0.02
  init_state:
    pos:
    - 0.0
    - 0.0
    - 0.6
    rot:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    lin_vel:
    - 0.0
    - 0.0
    - 0.0
    ang_vel:
    - 0.0
    - 0.0
    - 0.0
    default_joint_angles:
      LF_HAA: 0.0
      LH_HAA: 0.0
      RF_HAA: -0.0
      RH_HAA: -0.0
      LF_HFE: 0.4
      LH_HFE: -0.4
      RF_HFE: 0.4
      RH_HFE: -0.4
      LF_KFE: -0.8
      LH_KFE: 0.8
      RF_KFE: -0.8
      RH_KFE: 0.8
  noise:
    add_noise: false
    noise_level: 1.0
    noise_scales:
      dof_pos: 0.01
      dof_vel: 1.5
      lin_vel: 0.1
      ang_vel: 0.2
      gravity: 0.05
      height_measurements: 0.1
ppo:
  policy:
    init_noise_std: 1.0
    actor_hidden_dims:
    - 512
    - 512
    - 512
    critic_hidden_dims:
    - 512
    - 512
    - 512
    activation: elu
  algorithm:
    value_loss_coef: 1.0
    use_clipped_value_loss: true
    clip_param: 0.2
    entropy_coef: 0.0035
    num_learning_epochs: 5
    num_mini_batches: 4
    learning_rate: 0.0005
    schedule: adaptive
    gamma: 0.99
    lam: 0.95
    desired_kl: 0.01
    max_grad_norm: 1.0
  runner:
    num_steps_per_env: 24
    max_iterations: 15000
    save_interval: 50