### Config file for perceptive anymal RL


environment:
  name: "anymal_d" 
  env:
    num_envs: 2048
    num_observations: 107
    num_privileged_observations: 119
    env_spacing: 3.0
    num_actions: 12
    episode_length_s: 20  # seconds
    send_timeouts: True

  terrain:
    mesh_type: "plane"
    horizontal_scale: 0.1 # meters
    vertical_scale: 0.005 # meters
    border_size: 25 # meters
    curriculum: False
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    max_init_terrain_level: 5
    terrain_length: 8 # meters
    terrain_width: 8 # meters
    num_rows: 10  # number of terrain rows (levels)
    num_cols: 20  # number of terrain columns (types)

    # terrain types: [smooth slope, rough slope, stairs up, stairs down, discrete]
    terrain_proportions: [0.1, 0.1, 0.35, 0.25, 0.2]
    slope_treshold: 0.75
    measure_heights: False

  command:
    curriculum: False
    max_curriculum: 1.0
    num_commands: 4
    resampling_time: 10 # seconds
    heading_command: False
    ranges:
      lin_vel_x: [-0.50, 0.51] # min max [m/s]
      lin_vel_y: [-0.5, 0.5] # min max [m/s]
      ang_vel_yaw: [-0.5, 0.5] # min max [rad/s]
      heading: [-3.14, 3.14]

  asset:
    name: "anymal_d"
    default_dof_drive_mode: 3 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)
    collapse_fixed_joints: True
    replace_cylinder_with_capsule: True
    flip_visual_attachments: True
    fix_base_link: False
    density: 0.001
    angular_damping: 0.0
    linear_damping: 0.0
    max_angular_velocity: 1000.0
    max_linear_velocity: 1000.0
    armature: 0.0
    thickness: 0.01
    disable_gravity: False

    foot_name: "FOOT"
    shank_name: "SHANK"
    thigh_name: "THIGH"
    penalize_contacts_on: ["SHANK", "THIGH"]
    terminate_after_contacts_on: ["base"]
    self_collisions: 1 # 1 to disable, 0 to enable...bitwise filter

  normalization:
    obs_scales:
      lin_vel: 2.0
      ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05
      height_measurements: 1.0
      contact_forces: 0.0016666666666666668 # 1/600
    clip_observations: 100.0
    clip_actions: 100.0

  domain_randomization:
    randomize_friction: False
    friction_range: [0.5, 1.2]
    randomize_base_mass: False
    added_mass_range: [-5, 5]
    push_robots: False
    push_interval_s: 15 # sencods
    max_push_vel_xy: 1.0 # m/s

  sim:
    dt: 0.005
    substeps: 1
    gravity: [0.0, 0.0, -9.81] # [m/s^2]
    up_axis: 1  # 0 is y, 1 is z
    physics_engine: "physx"

    physx:
      num_threads: 10
      solver_type: 1  # 0: pgs, 1: tgs
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.01 # meters
      rest_offset: 0.0 # meters
      bounce_threshold_velocity: 0.5 # m/s
      max_depenetration_velocity: 1.0
      max_gpu_contact_pairs: 8388608 # 2**23
      default_buffer_size_multiplier: 5
      contact_collection: 1 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (broken - do not use!)

  control:
    control_type: "P"
    joints: ["HAA", "HFE", "KFE"]
    stiffness: [80.0, 80.0, 80.0]
    damping: [2.0, 2.0, 2.0]
    action_scale: 0.5
    decimation: 4

  viewer:
    ref_env: 0
    pos: [10.0, 0.0, 6.0] # meters
    lookat: [11.0, 5.0, 3.0] # meters

  rewards:
    base_height_target: 0.5
    max_contact_force: 500.0 # newtons
    only_positive_rewards: True
    tracking_sigma: 0.25
    soft_dof_pos_limit: 1.0
    soft_dof_vel_limit: 1.0
    soft_torque_limit: 1.0

    scales:
      termination: -0.0
      tracking_lin_vel: 0.0 # 1.0
      tracking_ang_vel: 0.0 # 0.5
      lin_vel_z: -0.0    # -2.0
      exp_base_position: 3.0
      exp_base_orientation: 1.0
      exp_base_linear_velocity: 2.0
      exp_base_angular_velocity: 1.0
      foot_power: -0.00
      ang_vel_xy: 0.0
      orientation: -0.
      torques: -0.00001
      dof_vel: -0.00
      dof_acc: -1.0e-6
      base_height: 0.0
      feet_air_time:  0.0
      collision: -0.0
      stumble: 0.0
      action_rate: -0.02
      stand_still: 0.0
      smoothness: -0.000
      swing_height: 0.0
      action_norm: -0.0005
      consistency: 20.0
      foot_position_tracking: 1.0
      z_height: 10.0

  init_state:
    pos: [0.0, 0.0, 0.6] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w
    lin_vel: [0.0, 0.0, 0.0] # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0] # x,y,z [rad/s]

    default_joint_angles:
      LF_HAA: 0.0
      LH_HAA: 0.0
      RF_HAA: -0.0
      RH_HAA: -0.0

      LF_HFE: 0.4
      LH_HFE: -0.4
      RF_HFE: 0.4
      RH_HFE: -0.4

      LF_KFE: -0.8
      LH_KFE: 0.8
      RF_KFE: -0.8
      RH_KFE: 0.8

  noise:
    add_noise: False
    noise_level: 1.0
    noise_scales:
      dof_pos: 0.01
      dof_vel: 1.5
      lin_vel: 0.1
      ang_vel: 0.2
      gravity: 0.05
      height_measurements: 0.1

ppo:
  policy:
    init_noise_std: 1.0
    actor_hidden_dims: [512, 512, 512]
    critic_hidden_dims: [512, 512, 512]
    activation: "elu"

  algorithm:
    value_loss_coef: 1.0
    use_clipped_value_loss: True
    clip_param: 0.2
    entropy_coef: 0.0035
    num_learning_epochs: 5
    num_mini_batches: 4 # mini batch size = num_envs*nsteps / num_mini_batches
    learning_rate: 0.0005
    schedule: "adaptive"
    gamma: 0.99
    lam: 0.95
    desired_kl: 0.01
    max_grad_norm: 1.0

  runner:
    num_steps_per_env: 24
    max_iterations: 1500
    save_interval: 50
    experiment_name: "perceptive_anymal_d"
